version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./src/launcher/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres

  axonserver:
    image: axoniq/axonserver:2023.2.1-jdk-17
    restart: unless-stopped
    ports:
     - "${AXON_SERVER_DASHBOARD_PORT}:8024"
     - "${AXON_SERVER_GRPC_PORT}:8124"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      AXONIQ_AXONSERVER_STANDALONE: "true"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    restart: unless-stopped
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--db=postgres", "--import-realm" ]
    ports:
      - "${KEYCLOAK_SERVER_PORT}:8080"
    depends_on:
      - postgres
