version: '3'
services:
  postgres-db:
    image: postgres:12-alpine
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./src/launcher/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres

  mongo-db:
    image: mongo:4
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - 'mongo-db:mongo'
    ports:
      - 8081:8081
