apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-express
spec:
  serviceName: mongo-express
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        selector: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: root
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: mongodevdb
          - name: ME_CONFIG_MONGODB_SERVER
            value: gridfs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  spec:
  ports:
  - name: mongo-express
    port: 80
    targetPort: 8081
  selector:
    app: mongo-express
