apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gridfs
spec:
  serviceName: gridfs
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
        selector: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo:4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongodevdb
          - name: MONGO_INITDB_DATABASE
            value: test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: gridfs
  labels:
    app: mongo-db
spec:
  spec:
  ports:
  - name: mongo-db
    port: 27017
    targetPort: 27017
  selector:
    app: mongo-db
