if-release: &if-release
    if: build.tag =~ /^[0-9]+\.[0-9]+\.[0-9]+\$/

if-our-repo: &if-our-repo
    if: pipeline.repository =~ /^https:\/\/github.com\/everest-engineering\//

if-main-branch: &if-main-branch
    if: build.branch == 'main'

steps:
  - label: ':hammer: Build & test'
    agents:
      java: 11
    commands:
      - pkill java || echo 'No Java processes to kill.'
      - ./gradlew startServer && ./gradlew build --console plain

  - label: ':sonarqube: Quality reporting'
    <<: *if-our-repo
    <<: *if-main-branch
    agents:
      java: 11
    commands:
      - pkill java || echo 'No Java processes to kill.'
      - ./gradlew clean startServer && ./gradlew codeCoverageReport sonarqube --console plain

  - wait:
    <<: *if-release

  - label: ':rocket: publish'
    <<: *if-release
    key: bintray-publish
    agents:
      java: 11
    commands:
      - git fetch --tags
      - ./gradlew bintrayPublish bintrayUpload --console plain
