if-our-repo: &if-our-repo
    if: pipeline.repository =~ /^https:\/\/github.com\/everest-engineering\//

if-main-branch: &if-main-branch
    if: build.branch == 'main'

steps:
  - label: ':hammer: Build & test'
    agents:
      java: 17
    commands:
      - ./gradlew clean build --console plain

  - label: ':sonarqube: Quality reporting'
    <<: *if-our-repo
    <<: *if-main-branch
    agents:
      java: 17
    commands:
      - ./gradlew clean codeCoverageReport sonar --console plain

